name: HwaSkyBlock
version: 'v1.0.9-bukkit'
main: org.hwabaeg.hwaskyblock.HwaSkyBlock
api-version: '1.13'

commands:
  섬:
    description: 섬 명령어를 이용합니다.
    usage: /섬
    aliases: [ island ]
  섬설정:
    description: 섬설정 명령어를 이용합니다.
    usage: /섬설정
    aliases: [ isset ]
  섬랭킹:
    description: 섬 랭킹을 표시합니다.
    usage: /섬랭킹
    aliases: [ isrk ]