name: HwaSkyBlock
version: 'v1.0.0-beta'
main: org.hwabeag.hwaskyblock.HwaSkyBlock
api-version: '1.13'

commands:
  섬:
    description: 섬 명령어를 이용합니다.
    usage: /섬
  섬설정:
    description: 섬설정 명령어를 이용합니다.
    usage: /섬설정
